### ISSUE TITLE
空控制器问题

### ISSUE THREAD

**Issue by cnzin** [liu21st/think#15]
很喜欢tp4无后缀轻简命名方式, 但是类名不得使用保留关键字来命名, 所以定义了`empty` 控制器后触发访问未定义控制器时就会报如下错  
 `syntax error, unexpected 'empty' (T_EMPTY), expecting identifier (T_STRING)`  
模块控制器等都去掉了层级后缀, 按照目前的规则在用户使用时可能常会遇到命名冲突.

**Comment by liu21st** [comment]
现在支持用户自定义 空控制器的名称了 默认改成 Error了
