### ISSUE TITLE
怎么从4直接变5了

### ISSUE THREAD

**Issue by chenjxlg** [liu21st/think#22]
怎么从4直接变5了?
版本跨越太快了吧

**Comment by liu21st** [comment]
其中原因很简单 当初的TP4里面有很多特性已经移植到后来的3.2版本，而TP4很长一段时间没有维护，此次更新较原来版本调整较大，我们认为用一个新的起点版本比较合适，就和当初PHP6一样

**Comment by chenjxlg** [comment]
那新版本预计什么时候发布呢,双12么,在成都和重庆的峰会上?
对PHP7的特性支持会不会提到日程上来呢

**Comment by kideny** [comment]
必须支持php7啊！
