### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xiaohome** [liu21st/think#34]
贵方 想把这个做强 这个可以理解！！

为什么不能 依赖一下 composer 的 第三方库呢  ， 说实话贵方的 model 确实很弱 ，
规范可以试着依赖一下 composer，里面拥有很多超强的库！！

**Comment by liu21st** [comment]
这并不影响用户使用composer的第三方优秀类库啊，话说TP为啥不能有自己的ORM类库呢

**Comment by xiaohome** [comment]
比如做一些 一对一 一对多 多对多 这样的关联的时候 确实很无力！！！
参考一下 [laravel-Eloquent: Relationships](http://laravel.com/docs/5.1/eloquent-relationships)

**Comment by kideny** [comment]
对第三方耦合度太高，不见得是好事。很快就会变成，核心追着第三方类库走了。
Model作为框架的核心，强化自身远远比依赖第三方好。
我的建议是，强化自身类库的同时，增强扩展。

**Comment by liu21st** [comment]
@xiaohome 如果用composer里面的类库组装出一个框架 这是用户就可以做的事情 不需要thinkphp来做了。只要不断完善和创新就有希望走出自己的路 ~ TP从 路由 控制器 模板引擎 ORM 日志 缓存都是独立开发，然而这些类库composer都有，我们的目标是让用户用TP的类库来自己组装出自己的框架 这也是TP5会努力的方向

**Comment by liuzhaowei55** [comment]
现在这个版本就很好，可以直接用composer require命令然后在index.php引入下就行了，希望现在的3.2.3可以无痛升级

**Comment by liu21st** [comment]
@liuzhaowei55 你这要求有点高 无痛升级 规范都不一样了 控制器写法区别较大而且 ~ 不过按照惯例 官方会给出升级指导文件的

**Comment by liuzhaowei55** [comment]
@liu21st 能剧透下12号会出一个稳定的版本吗？
