### ISSUE TITLE
为何不从PHP5.5开始？

### ISSUE THREAD

**Issue by goldeagle** [liu21st/think#4]
TP4 多了很多我很喜欢的特性，希望能够快速成熟起来。如果可以，我们也打算围绕TP4做一些相关的组件和模块。

不过，既然是new branch了，为何不采用更新的 PHP 5.5.x？应该到下半年的时候正好 PHP5.5 正式版也会推出了。反正 TP4 是没啥可能跑在现在国内的主流虚机上的了，不如直接用最新技术。

**Comment by shellus** [comment]
laravel5.1已经最低要求php5.5.9+了。。。

**Comment by kideny** [comment]
原来2013年，就有Thinkphp4了，哈哈。
