### ISSUE TITLE
Declaration of traits\model\Relation::_after_find() should be compatible with think\Model::_after_find(&$result)

### ISSUE THREAD

**Issue by liuzhaowei55** [liu21st/think#49]
`E_STRICT: Declaration of traits\model\Relation::_after_find() should be compatible with think\Model::_after_find(&$result) in /thinkphp/library/think/model/Relation.php on line 18`
`E_STRICT: Declaration of traits\model\Relation::_after_select() should be compatible with think\Model::_after_select(&$resultSet) in /thinkphp/library/think/model/Relation.php on line 18`
方法重写参数$options应该需要一个默认值 $options = [];

**Comment by liu21st** [comment]
感谢反馈 已经修正~
