### ISSUE TITLE
/thinkphp/library/think/model.php 关于count()等方法

### ISSUE THREAD

**Issue by liuzhaowei55** [liu21st/think#52]
thinkphp3时候的一些用__call()实现的方法现在没有了,count()等功能以后该怎么操作?

**Comment by zhaishuaigan** [comment]
有个adv模型, 里面有

**Comment by liuzhaowei55** [comment]
@zhaishuaigan 
Adv模型的推荐用法是什么?
自己新建一个类然后继承这个类去调用,还是直接使用这个类?

**Comment by zhaishuaigan** [comment]
不知道啊, 我这两天才刚测试, 估计还在调整, 到时候可能还会把__call移动到基础模型里面

**Comment by liu21st** [comment]
现在的基础model是基础功能 需要的时候 自己继承其它的扩展模型类即可~ 高级查询/视图模型/关联模型都是如此，亦可自己通过traits组装
