### ISSUE TITLE
想加入新框架的编写工作，贡献自己的代码，请问如何加入和协同，有没有相关计划！

### ISSUE THREAD

**Issue by niltor** [liu21st/think#57]
想加入新框架的编写工作，贡献自己的代码，请问如何加入和协同，有没有相关计划！
希望能尽快完成这个分支的编写，很多人等着用，但是，还需要更多人参与进来。
TP从一开始到现在，共同奉献代码这块还太有限，不是很利于发展。大家都是捡现成的用。
希望更多时间能关注一下，如果协同安排任务，让更多优秀的开发者一块加入进来，相信慢慢的会更有影响力。

**Comment by liu21st** [comment]
嗯 协同这块以后会加强 欢迎加入 可以加入我们的QQ群：221895784
