### ISSUE TITLE
syntax error, unexpected '.', expecting ']' 

### ISSUE THREAD

**Issue by chenjxlg** [liu21st/think#60]
错误位置 FILE: /disk/www/think5/thinkphp/library/think/template.php 　LINE: 35

**Comment by kinosang** [comment]
同样的问题

**Comment by Lofanmi** [comment]
@kinosang 你用什么php版本

**Comment by kinosang** [comment]
@Lofanmi 5.5 5.6 7.0均出现此错误，5.4未测试
